### ISSUE TITLE
Leak test

### ISSUE THREAD

**Issue by joshp23** [LinxGem33/IP-Finder#1]
This is a pretty nifty extension, especially for testing VPN status. It might be neat to have a link to a leak test service, like [IP Leak](https://ipleak.net/), or to utilize their [api](https://airvpn.org/topic/14737-api/) for extended leak testing.

**Comment by survivor303** [comment]
I published this in the extension page comments too but I put in on here also.

It is great but make it possible to copy that IP address and hostname to clipboard when you click on it from drop down menu.

**Comment by LinxGem33** [comment]
@joshp23 
appreciate the feed back, your suggestion is defiantly something I'm going to add to the TO DO list I'm currently working on gnome 3.24 shell integration once thats finished and updated on gnome extensions  i can then concentrate on new features.

kind regards
