### ISSUE TITLE
Flag icons do not appear

### ISSUE THREAD

**Issue by The9Cat** [LinxGem33/IP-Finder#11]
The flag icon does not appear using Ubuntu 17.04.  Just a ? in a box.  The pulldown provides the correct location and IP.  I installed from gnome.extensions.org.

**Comment by LinxGem33** [comment]
@The9Cat
## 
please see below ive tested on ubuntu gnome 17.04 and the flags are working i also installed from extensions.gnome.org also make sure your connected to the Internet also please see this wiki guide on how to [report bugs](https://github.com/LinxGem33/Arc-Menu/wiki/Reporting-Bug's)
##
![fli](https://user-images.githubusercontent.com/19158615/28716055-60b39df6-739b-11e7-8e0c-50a9dce82cdf.png)
##
kind regards

**Comment by The9Cat** [comment]
Okay, thanks for the info.  I did some more digging. The situation appears to be VPN related.  If I shutdown my VPN (which is supplied by PIA), and revert to my ISP,  my US location is correctly detected.  If I use a VPN server in (e.g.) Ireland, it seems to work.  If I then return to my original VPN server, the Ireland flag icon and google location remains.  I'm not sure what is going on here.  Seems to be a particular server IP that's confusing the algorithm.  If I manually select a different US server, it works as well.

It's not a big deal either way.  I will remark that I had been using "Public IP Address" before upgrading to 17.04 and that worked correctly with the VPN server; but this extension doesn't work with gnome-shell 3.24.2.

 Here is the information you requested.

**Information about distribution**

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

**Gnome-shell version**
3.24.2

**Logs from the systemd journal**

Nothing reported when extension is loaded or in operation.

**Comment by LinxGem33** [comment]
@The9Cat 
##
appreciate the feed back, it shouldn’t make a difference if if your behind a VPN, ip finder would just display the ipv4 connection no matter if its public or private, as you stated that

>  If I use a VPN server in (e.g.) Ireland, it seems to work. If I then return to my original VPN server, the Ireland flag icon and google location remains

which leads me to believe that ip finder is functioning properly.
##
kind regards

**Comment by The9Cat** [comment]
No, it is not working correctly.  Or at least not as I expect.  If I go from Ireland back to the US, I would expect the US flag to show up, not the Ireland flag.

**Comment by LinxGem33** [comment]
@The9Cat 

easiest way to test to know for sure is to test in a virtual machine if you can do this a post back your results.

kind regards

**Comment by LinxGem33** [comment]
@The9Cat 
please see below a screen capture, i tested different locations and they changed a interval of 30 seconds was set in the settings so i am unsure what your issue is as the flag changes seem to work.
##
![ipc](https://user-images.githubusercontent.com/19158615/28720336-ca6c8eb6-73a4-11e7-8454-1e14ae1e2d06.gif)
##
kind regards
