### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by survivor303** [LinxGem33/IP-Finder#2]
I published this in the extension page comments too but I put in on here also.

It is great but make it possible to copy that IP address and hostname to clipboard when you click on it from drop down menu.

**Comment by LinxGem33** [comment]
@survivor303 
appreciate the feed back, your suggestion is defiantly something I'm going to add to the TO DO list I'm currently working on gnome 3.24 shell integration for the up coming 17.04 release once thats finished and updated on gnome extensions i can then concentrate on new features.

kind regards
