### ISSUE TITLE
https calls to ipinfo.io

### ISSUE THREAD

**Issue by coderholic** [LinxGem33/IP-Finder#3]
You can now call https://ipinfo.io over https, as it's no longer limited to paid plans: https://twitter.com/ipinfoio/status/779374440417103872

**Comment by coderholic** [comment]
You also don't need to lookup the IP first and then pass it into ipinfo - if you don't pass in an IP it'll give you details for your current IP anyway, eg:

```
$ curl ipinfo.io
{
  "ip": "24.5.144.36",
  "hostname": "c-24-5-144-36.hsd1.ca.comcast.net",
  "city": "Mountain View",
  "region": "California",
  "country": "US",
  "loc": "37.4192,-122.0574",
  "org": "AS7922 Comcast Cable Communications, LLC",
  "postal": "94043"
}
```

**Comment by LinxGem33** [comment]
@coderholic 
really appreciate the info, Ill incorporate the HTTPS calls hopefully in the next release.

kind regards
