### ISSUE TITLE
Doesn't seem to install on Gnome 3.24.0

### ISSUE THREAD

**Issue by CliffS** [LinxGem33/IP-Finder#5]
I have just upgraded to Ubuntu 17.04 and this extension is refusing to install.

I know that's not much of a bug report.  What information would be more useful?

**Comment by LinxGem33** [comment]
@CliffS 

I’ve just this minute tested the extension in a virtual environment and your right its not installing which is strange as it was working in the beta version i think its a packaging error from gnome extensions but I’m looking at the code now and i cant see any coding error, ill try upload another version or maybe disable my previous version and see if it works sorry for the inconvenience.

kind regards

**Comment by CliffS** [comment]
Wow.  Quick response.

Look forward to an update in strict mode.

**Comment by CliffS** [comment]
Any update on this?  It's such a useful extension.

**Comment by LinxGem33** [comment]
@CliffS 
hi I'm still going over the code I've made a few updates to the API and once I've finished ill get started on the gnome 3.24 integration I'm just waiting for conformation to what the new shell standards are then i can start.

kind regards

**Comment by seeker2921** [comment]
@LinxGem33
How is the syntax reformating coming along? I attempted to look for specs but did not have much luck myself, I am wondering if you are encountering similar issues?

**Comment by LinxGem33** [comment]
@seeker2921 

appreciate the feed back, I’m still confused as to what the issue maybe but i cant seem to pin point the issue as I’m still new to gtk and gnome shell development as i said previously any help is welcome to pin point this issue.

kind regards

**Comment by cocoahooves** [comment]
JS ERROR: Exception in callback for signal: extension-found: Error: Requiring GtkClutter, version none: Requiring namespace 'Clutter' version '1.0', but '0' is already loaded
                                                         @/home/rls/.local/share/gnome-shell/extensions/IP-Finder@linxgem33.github.com/extension.js:34:7
                                                         initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:221:5
                                                         loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:168:18
                                                         _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:312:9
                                                         _emit@resource:///org/gnome/gjs/modules/signals.js:126:27
                                                         ExtensionFinder<._loadExtension@resource:///org/gnome/shell/misc/extensionUtils.js:184:9
                                                         wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                                         bind/<@resource:///org/gnome/gjs/modules/lang.js:95:16
                                                         collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:1
                                                         ExtensionFinder<.scanExtensions@resource:///org/gnome/shell/misc/extensionUtils.js:189:9
                                                         wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
                                                         _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:314:5
                                                         enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:322:9
                                                         _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:353:9
                                                         init@resource:///org/gnome/shell/ui/extensionSystem.js:361:5
                                                         _initializeUI@resource:///org/gnome/shell/ui/main.js:219:5
                                                         start@resource:///org/gnome/shell/ui/main.js:127:5
                                                         @<main>:1:31

**Comment by LinxGem33** [comment]
@cocoahooves 

now merged with main branch thank you :smile:
